### ISSUE TITLE
wiki pages always get generated at $cwd

### ISSUE THREAD

**Issue by nkoehring** [TeddyDD/kakoune-wiki#1]
Wiki pages are only recognized as long as I am in the set wiki folder. Everywhere else the plugin looks right at the current directory for files.

In my kakrc is the setting `wiki_setup "/home/nk/Wiki"` coming after `colorscheme` and some `set-options`s.
Kakoune is compiled from [tree v2018.04.13](https://github.com/mawww/kakoune/tree/v2018.04.13) on Void Linux (Kernel 4.17.1_1, musl build).
```
*** This is the debug buffer, where debug info will be written ***
Dependency unmet: gocode, please install it to use go-tools
Dependency unmet: goimports, please install it to use go-tools
Dependency unmet: gogetdoc, please install it to use go-tools
error running hook BufCreate(*scratch*)/: 1:1: 'editorconfig-load' 37:1684: 'hook' regex parse error: unexpected '*' at '<<<HERE>>>*scratch*'
```

**Comment by TeddyDD** [comment]
Do you use autoloads or source wiki plugin manually?
Do you use `wiki` command to create new wiki page? If so:I  `wiki` command is just for editing (it's a wrapped `edit` with path completion for quick navigation), you have to use `wiki_new_page` or `@page` syntax on exising page (note that `@page` syntax works only on exising wiki pages). I should probably change that.

Otherwise I have no idea whats  broken. I use Void as well (glibc version), I use the same version of Kakoune :confused: 

We might try one more thing. `wiki_setup` is just synax sugar for two commands:

```
set-option global wiki_path /home/nk/Wiki
hook global BufCreate /home/nk/Wiki/.+\.md %{ wiki_enable }
```
try using them instead, we will see what happens.

> Wiki pages are only recognized as long as I am in the set wiki folder. Everywhere else the plugin looks right at the current directory for files.

So if your cwd equals wiki directory, :wiki command shows list of filses, but everywhere else list is empty?

**Comment by nkoehring** [comment]
Autoload

**Comment by TeddyDD** [comment]
I'm currently rewriting some of the internals to support nested directories in `@tag` syntax and to make `wiki` command friendlier. We will see if this fix the issue. I'll try to push the update in few hours :)

**Comment by TeddyDD** [comment]
Ok, done, check out new README and tell me if it works for you :)

**Comment by nkoehring** [comment]
Sorry, it took a while. Now I can just use `:wiki` and it works as expected. Thanks!
